monolog :
  channels :
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - audit
when@dev :
  monolog :
    handlers :
      main :
        type : stream
        path : "%kernel.logs_dir%/%kernel.environment%.log"
        level : debug
        formatter : monolog.formatter.main_log_formatter
        channels : [ "!event" ]
      console :
        type : console
        process_psr_3_messages : false
        channels : [ "!event", "!doctrine", "!console" ]

when@prod :
  monolog :
    handlers :
      audit :
        level : debug
        type : stream
        path : '%kernel.logs_dir%/audit.log'
        channels : [ audit ]
      main :
        type : fingers_crossed
        action_level : error
        level : error
        channels : [ "!event", "!doctrine", "!security" ]
        handler : nested
        excluded_http_codes : [ 404, 405 ]
        buffer_size : 20 # How many messages should be saved? Prevent memory leaks
      security :
        # log all messages (since debug is the lowest level)
        level : info
        type : stream
        path : '%kernel.logs_dir%/security.log'
        channels : [ security ]
      nested :
        type : stream
        path : "%kernel.logs_dir%/%kernel.environment%.log"
        level : debug
      console :
        type : console
        process_psr_3_messages : false
        channels : [ "!event", "!doctrine" ]

when@test :
  monolog :
    handlers :
      audit :
        level : debug
        type : stream
        path : '%kernel.logs_dir%/%kernel.environment%.audit.log'
        channels : [ audit ]
      main :
        type : fingers_crossed
        action_level : error
        channels : [ "!event", "!doctrine", "!security" ]
        handler : nested
        excluded_http_codes : [ 404, 405 ]
        buffer_size : 50 # How many messages should be saved? Prevent memory leaks
      security :
        # log all messages (since debug is the lowest level)
        level : info
        type : stream
        path : '%kernel.logs_dir%/%kernel.environment%.security.log'
        channels : [ security ]
      nested :
        type : stream
        path : "%kernel.logs_dir%/%kernel.environment%.log"
        level : debug
      console :
        type : console
        process_psr_3_messages : false
        channels : [ "!event", "!doctrine" ]